import { User, InventoryItem, CapitalItemRequest, Notification, MaintenanceLog, ItemIssue, Activity, StockAlert } from './types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Dr. K. Rajaratnam',
    email: 'admin@eng.jfn.ac.lk',
    role: 'admin',
    department: 'ADMIN',
    phone: '+94 21 222 0000',
    isActive: true,
    createdAt: new Date('2023-01-15'),
    lastLogin: new Date(),
  },
  {
    id: '2',
    name: 'Prof. S. Sivakumar',
    email: 'hod.eee@eng.jfn.ac.lk',
    role: 'hod',
    department: 'EEE',
    phone: '+94 21 222 0001',
    isActive: true,
    createdAt: new Date('2023-02-10'),
    lastLogin: new Date(),
  },
  {
    id: '3',
    name: 'Dr. T. Thayaparan',
    email: 'hod.ce@eng.jfn.ac.lk',
    role: 'hod',
    department: 'CE',
    phone: '+94 21 222 0002',
    isActive: true,
    createdAt: new Date('2023-02-12'),
    lastLogin: new Date(),
  },
  {
    id: '4',
    name: 'Mr. V. Vijayakumar',
    email: 'labincharge.eee@eng.jfn.ac.lk',
    role: 'lab_incharge',
    department: 'EEE',
    phone: '+94 21 222 0003',
    isActive: true,
    createdAt: new Date('2023-03-05'),
    lastLogin: new Date(),
  },
  {
    id: '5',
    name: 'Mrs. P. Premila',
    email: 'ma@eng.jfn.ac.lk',
    role: 'ma',
    department: 'ADMIN',
    phone: '+94 21 222 0004',
    isActive: true,
    createdAt: new Date('2023-03-10'),
    lastLogin: new Date(),
  },
  {
    id: '6',
    name: 'Mr. R. Ranjan',
    email: 'labto.ce@eng.jfn.ac.lk',
    role: 'lab_to',
    department: 'CE',
    phone: '+94 21 222 0005',
    isActive: true,
    createdAt: new Date('2023-04-01'),
    lastLogin: new Date(),
  },
];

// Mock Inventory Items
export const mockInventoryItems: InventoryItem[] = [
  {
    id: '1',
    name: 'Digital Oscilloscope',
    description: 'Tektronix TBS1102B 100MHz Digital Oscilloscope',
    category: 'lab_equipment',
    department: 'EEE',
    lab: 'Electronics Lab',
    quantity: 15,
    availableQuantity: 12,
    unitPrice: 85000,
    totalValue: 1275000,
    status: 'available',
    condition: 'excellent',
    location: 'EEE Building, Room 102',
    supplier: 'Tektronix Sri Lanka',
    purchaseDate: new Date('2023-06-15'),
    warrantyExpiry: new Date('2026-06-15'),
    minStockLevel: 5,
    serialNumber: 'TBS1102B-001',
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Function Generator',
    description: 'Keysight 33210A Function Generator 10MHz',
    category: 'lab_equipment',
    department: 'EEE',
    lab: 'Communications Lab',
    quantity: 20,
    availableQuantity: 18,
    unitPrice: 45000,
    totalValue: 900000,
    status: 'available',
    condition: 'good',
    location: 'EEE Building, Room 105',
    minStockLevel: 8,
    createdAt: new Date('2023-07-20'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Computer Workstation',
    description: 'Dell OptiPlex 7090 i7 16GB RAM',
    category: 'lab_equipment',
    department: 'CE',
    lab: 'Computer Lab 1',
    quantity: 40,
    availableQuantity: 38,
    unitPrice: 175000,
    totalValue: 7000000,
    status: 'available',
    condition: 'excellent',
    location: 'CE Building, Room 201',
    supplier: 'Dell Technologies',
    purchaseDate: new Date('2024-01-10'),
    warrantyExpiry: new Date('2027-01-10'),
    minStockLevel: 10,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Office Chair - Executive',
    description: 'Ergonomic Executive Office Chair with Lumbar Support',
    category: 'furniture',
    department: 'ADMIN',
    quantity: 25,
    availableQuantity: 20,
    unitPrice: 35000,
    totalValue: 875000,
    status: 'available',
    condition: 'good',
    location: 'Administration Building',
    minStockLevel: 5,
    createdAt: new Date('2023-05-10'),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Laboratory Table',
    description: 'Chemical Resistant Laboratory Table 180x90cm',
    category: 'furniture',
    department: 'CVE',
    lab: 'Materials Testing Lab',
    quantity: 12,
    availableQuantity: 12,
    unitPrice: 55000,
    totalValue: 660000,
    status: 'available',
    condition: 'excellent',
    location: 'CVE Building, Room 103',
    minStockLevel: 4,
    createdAt: new Date('2023-08-15'),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'CNC Milling Machine',
    description: 'Haas VF-2 CNC Vertical Milling Machine',
    category: 'lab_equipment',
    department: 'ME',
    lab: 'Manufacturing Lab',
    quantity: 2,
    availableQuantity: 1,
    unitPrice: 2500000,
    totalValue: 5000000,
    status: 'in_use',
    condition: 'good',
    location: 'ME Workshop',
    supplier: 'Haas Automation',
    purchaseDate: new Date('2022-11-20'),
    warrantyExpiry: new Date('2025-11-20'),
    minStockLevel: 1,
    createdAt: new Date('2022-11-20'),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: '3D Printer',
    description: 'Ultimaker S5 Professional 3D Printer',
    category: 'lab_equipment',
    department: 'IDS',
    lab: 'Innovation Lab',
    quantity: 3,
    availableQuantity: 2,
    unitPrice: 450000,
    totalValue: 1350000,
    status: 'available',
    condition: 'excellent',
    location: 'IDS Building, Room 101',
    minStockLevel: 1,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: 'Total Station',
    description: 'Leica TS16 Robotic Total Station',
    category: 'lab_equipment',
    department: 'CVE',
    lab: 'Survey Lab',
    quantity: 4,
    availableQuantity: 1,
    unitPrice: 1200000,
    totalValue: 4800000,
    status: 'in_use',
    condition: 'good',
    location: 'CVE Building, Room 001',
    minStockLevel: 2,
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date(),
  },
];

// Mock Capital Item Requests
export const mockRequests: CapitalItemRequest[] = [
  {
    id: '1',
    requestNumber: 'REQ-2024-001',
    requestedBy: mockUsers[5],
    department: 'CE',
    category: 'lab_equipment',
    items: [
      {
        id: '1',
        name: 'Network Switch 48-Port',
        description: 'Cisco Catalyst 9300 48-Port PoE+ Switch',
        quantity: 3,
        estimatedUnitPrice: 450000,
      },
      {
        id: '2',
        name: 'Server Rack',
        description: '42U Server Rack Cabinet',
        quantity: 1,
        estimatedUnitPrice: 180000,
      },
    ],
    justification: 'Upgrade network infrastructure for new computer labs',
    priority: 'high',
    status: 'pending',
    totalEstimatedCost: 1530000,
    remarks: [],
    approvalChain: [
      { role: 'lab_incharge', status: 'pending' },
      { role: 'hod', status: 'pending' },
      { role: 'admin', status: 'pending' },
    ],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    requestNumber: 'REQ-2024-002',
    requestedBy: mockUsers[4],
    department: 'ADMIN',
    category: 'furniture',
    items: [
      {
        id: '1',
        name: 'Conference Table',
        description: 'Modern Conference Table 12-seater',
        quantity: 2,
        estimatedUnitPrice: 120000,
      },
    ],
    justification: 'New meeting room furniture requirement',
    priority: 'medium',
    status: 'approved_by_hod',
    totalEstimatedCost: 240000,
    remarks: [
      {
        id: '1',
        userId: '2',
        userName: 'Prof. S. Sivakumar',
        userRole: 'hod',
        remark: 'Approved. Please proceed with procurement.',
        createdAt: new Date('2024-01-18'),
      },
    ],
    approvalChain: [
      { role: 'hod', status: 'approved', userId: '2', userName: 'Prof. S. Sivakumar', timestamp: new Date('2024-01-18') },
      { role: 'admin', status: 'pending' },
    ],
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-18'),
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    title: 'Low Stock Alert',
    message: 'Digital Multimeter stock is below minimum threshold',
    type: 'warning',
    isRead: false,
    link: '/admin/inventory',
    createdAt: new Date(),
  },
  {
    id: '2',
    userId: '1',
    title: 'New Request',
    message: 'New capital item request REQ-2024-001 awaiting approval',
    type: 'info',
    isRead: false,
    link: '/admin/requests',
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: '3',
    userId: '1',
    title: 'Purchase Completed',
    message: 'Office furniture purchase order completed successfully',
    type: 'success',
    isRead: true,
    createdAt: new Date(Date.now() - 86400000),
  },
];

// Mock Maintenance Logs
export const mockMaintenanceLogs: MaintenanceLog[] = [
  {
    id: '1',
    item: mockInventoryItems[0],
    type: 'preventive',
    description: 'Annual calibration and maintenance',
    reportedBy: mockUsers[5],
    assignedTo: 'External Service Provider',
    status: 'scheduled',
    scheduledDate: new Date('2024-02-15'),
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    item: mockInventoryItems[5],
    type: 'corrective',
    description: 'Spindle motor replacement needed',
    reportedBy: mockUsers[5],
    status: 'in_progress',
    scheduledDate: new Date('2024-01-25'),
    cost: 150000,
    createdAt: new Date('2024-01-22'),
  },
];

// Mock Item Issues
export const mockItemIssues: ItemIssue[] = [
  {
    id: '1',
    item: mockInventoryItems[0],
    issuedTo: 'Mr. A. Arulanantham (EE4001)',
    issuedBy: mockUsers[5],
    purpose: 'Final Year Project',
    quantity: 2,
    issueDate: new Date('2024-01-10'),
    expectedReturnDate: new Date('2024-03-15'),
    status: 'issued',
  },
  {
    id: '2',
    item: mockInventoryItems[2],
    issuedTo: 'Lab Session - CE3020',
    issuedBy: mockUsers[5],
    purpose: 'Programming Lab Session',
    quantity: 25,
    issueDate: new Date('2024-01-22'),
    expectedReturnDate: new Date('2024-01-22'),
    actualReturnDate: new Date('2024-01-22'),
    status: 'returned',
    condition: 'good',
  },
];

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: '1',
    action: 'Item Added',
    description: 'Added 5 new computer workstations to CE inventory',
    user: 'Dr. K. Rajaratnam',
    timestamp: new Date(),
    type: 'create',
  },
  {
    id: '2',
    action: 'Request Approved',
    description: 'Approved furniture request REQ-2024-002',
    user: 'Prof. S. Sivakumar',
    timestamp: new Date(Date.now() - 3600000),
    type: 'approve',
  },
  {
    id: '3',
    action: 'Item Issued',
    description: 'Issued 2 oscilloscopes to Final Year Project student',
    user: 'Mr. R. Ranjan',
    timestamp: new Date(Date.now() - 7200000),
    type: 'issue',
  },
  {
    id: '4',
    action: 'Stock Updated',
    description: 'Received new batch of office chairs (qty: 15)',
    user: 'Mrs. P. Premila',
    timestamp: new Date(Date.now() - 86400000),
    type: 'update',
  },
];

// Mock Stock Alerts
export const mockStockAlerts: StockAlert[] = [
  {
    id: '1',
    item: mockInventoryItems[1],
    alertType: 'low_stock',
    message: 'Function Generator stock below minimum threshold (8)',
    isResolved: false,
    createdAt: new Date(),
  },
  {
    id: '2',
    item: mockInventoryItems[7],
    alertType: 'low_stock',
    message: 'Total Station availability critically low',
    isResolved: false,
    createdAt: new Date(Date.now() - 3600000),
  },
];

// Dashboard Statistics
export const getDashboardStats = (role: string, department?: string) => {
  return {
    totalItems: 1161,
    totalValue: 21860000,
    pendingRequests: 5,
    lowStockItems: 8,
    itemsInMaintenance: 3,
    recentActivities: mockActivities,
  };
};
